# Problem Set 2

## Problem 5 - Section 2.6 - Question 25

In [8]:
import numpy as np
from scipy.linalg import toeplitz, lu

In [9]:
# Create Toeplitz matrix
K = toeplitz([2, -1, 0, 0, 0, 0])

# LU decomposition (SciPy returns P, L, U)
P, L, U = lu(K) # type: ignore

# Inverse of L
L_inv = np.linalg.inv(L)

print(L_inv)

[[1.         0.         0.         0.         0.         0.        ]
 [0.5        1.         0.         0.         0.         0.        ]
 [0.33333333 0.66666667 1.         0.         0.         0.        ]
 [0.25       0.5        0.75       1.         0.         0.        ]
 [0.2        0.4        0.6        0.8        1.         0.        ]
 [0.16666667 0.33333333 0.5        0.66666667 0.83333333 1.        ]]


## Problem 6 - Section 2.6 - Question 26

In [10]:
Big = np.array([[6, 5, 4, 3, 2, 1], 
                [5, 10, 8, 6, 4, 2], 
                [4, 8, 12, 9, 6, 3], 
                [3, 6, 9, 12, 8, 4], 
                [2, 4, 6, 8, 10, 5], 
                [1, 2, 3, 4, 5, 6]])
print(K @ Big)

[[7 0 0 0 0 0]
 [0 7 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 7 0]
 [0 0 0 0 0 7]]
